name: 'fadiquader/pr-semver-bump'
description: 'Create a new Semantic Version for Pull Request'
branding:
  icon: anchor
  color: blue
inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
outputs:
  NEXT_VERSION:
    description: 'Next version'
runs:
  using: node16
  main: dist/index.js
