name: Pull Request Version Bump
description: 'Create a new semantic version that is automatically committed and pushed to your Pull Request'
branding:
  icon: anchor
  color: blue
inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
outputs:
  NEXT_VERSION:
    description: 'Next version'
runs:
  using: node16
  main: dist/index.js
