name: 'Create new Semantic Version'
description: 'Create new Semantic Version for Pull Request'
inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
runs:
  using: node16

  main: dist/index.js
  post: dist/index.js
