name: 'Bump Version'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: 'actions/checkout@v3'
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

